### ISSUE TITLE
TBAdvertisingMessage is 0x15 on new devices

### ISSUE THREAD

**Issue by DRCombes** [iskalchev/ThermoBeacon-pyhap#39]
Hi!

Thanks for your excellent library which has been brilliant for my home heat-loss monitoring project;  many thanks!

I've just added a few more ThermoBeacons to my project, and have discovered that they're issuing their data message using message id 0x15 instead of 0x10 or 0x11 as expected.

Happy to gather any evidence you need to support making changes to the library, although please note I'm a novice when it comes to python code development.

Many thanks,
David

**Comment by iskalchev** [comment]
Hi,

I added this ID (0x15), but I'm not sure if the message format is the same.
Please test if everything is OK.

What model is the device? Can you send me a link?

Regards,
Ivko

**Comment by DRCombes** [comment]
Hi Ivko,

Thanks for the prompt response.  I have tested the revised tp_protocol.py with my devices and the data messages appear to be the same format, as the information is coming through OK.

The devices look identical to the previous batch, which I bought in March 2021.  They are the BriFit Wireless Thermometer Hygrometer, purchased from UK Amazon:

https://smile.amazon.co.uk/gp/product/B08GWVLXZ3/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1

Many thanks,
David
